spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://backjin.iptime.org:3306/app_test_db
    username: app_user
    password: wlsdnr7^^
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate: org.hibernate.dialect.MySQLDialect
  data:
    mongodb:
      database: app_db
      uri: mongodb://app_user:wlsdnr7^^@backjin.iptime.org:27017

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa
  expiration_time: 3600
  refresh_time: 1209600


